services:
  - type: web
    name: petbook-ao-api
    runtime: node
    repo: https://github.com/Petbook-ao/petbook-ao-api
    branch: adilson/production  # Foco específico na branch adilson/production
    plan: free
    region: oregon
    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: npm run start:prod
    autoDeployTrigger:
      branch: adilson/production  # Só dispara deploy quando houver push na adilson/production
    envVariables:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: $DATABASE_URL
      JWT_SECRET: $JWT_SECRET
    healthCheckPath: /api/health
    httpPort: 3000

  - type: postgres  # Serviço de banco de dados
    name: petbook-db
    plan: free
    region: oregon
    version: '14'
    
version: "1"